### ISSUE TITLE
Django upgrade 1.5

### ISSUE THREAD

**Issue by swistak35** [iiuni/projektzapisy#115]
I've started to checking out what have to be needed to upgrade Django to 1.5. (I have #8 in mind for reference)

# ToDO:
- [x] Merge first PR with safe changes: #106 
- [ ] `/home/vagrant/env2.7/lib/python2.7/site-packages/django/core/managemen /__init__.py:465: DeprecationWarning: The 'execute_manager' function is deprecated, you likely need to update your 'manage.py'; please see the Django 1.4 release notes (https://docs.djangoproject.com/en/dev/releases/1.4/).  DeprecationWarning)`
- [ ] `/home/vagrant/env2.7/lib/python2.7/site-packages/django/core/management/__init__.py:409: DeprecationWarning: The 'setup_environ' function is deprecated, you likely need to update your 'manage.py'; please see the Django 1.4 release notes (https://docs.djangoproject.com/en/dev/releases/1.4/).  DeprecationWarning)`
- [ ] fix all places with `request.user.student` and `request.user.employee`

# ToDo after migrating to 1.5
- [ ] revert https://github.com/lewymati/projektzapisy/pull/106/commits/5252c8f3b3e23fbf0d280ca69dfbcb970d67d53d - it is not needed anymore in 1.5
