### ISSUE TITLE
Infra roadmap

### ISSUE THREAD

**Issue by swistak35** [iiuni/projektzapisy#13]
- [x] Read http://rogueleaderr.com/post/65157477648/the-idiomatic-guide-to-deploying-django-in
- [x] Make chefable environment
- [x] Add monitoring, for example: new relic
- [x] Encryption of secrets
- [x] Add useful tools
  - [x] htop
- [x] Clean up the settings.py, make it versioned in a system
- [x] Add error tracking software: rollbar looks like the one which is free and supports python2.6
  - It works! It just needs an upgrade of `six` to `1.9.0`
- [x] Clean directories which should be linked on production/staging systems (`logs/`, at least)
- [x] Add logs with logrotate [ logs are rotated, but not with the logrotate. Setup was annoying as fuck, it may be easier to do it right when on newer versions of Django and/or python ]
- [x] CircleCI setup
  - [x] Notifications to slack
  - [x] Github PR CI badges
- [x] Make deployment with switchable releases
- [x] Queue tools (Celery, RabbitMQ) [ I would postpone until we'll be on python >= 2.7]
- [x] Backups
- [x] NewRelic monitoring for Django application
- [x] Accounts
  - [x] new relic
  - [x] rollbar
- [x] Find better domain than my personal zapisyuwr.swistak35.com for staging
- [x] Make deploy install packages
- [x] Make deploy run migrations
