### ISSUE TITLE
Setting up staging sever

### ISSUE THREAD

**Issue by voter101** [iiuni/projektzapisy#6]
# Description

Our server runs on the II's VPS. Machine has whole environment setup in bare-bone style. It needs some more attention.

Right now everything runs on unattached server process running on the machine. It is not really secure and requires work on automating deploys.

Good thing to think about - do we really need to automate this process? I am not that sure... IMO, just git pulling by hand is enough.
## Run server

1) Enter `all@156.17.4.42`
2) Get into `var/lib/projektzapisy/zapisy` and run `nohup python manage.py runserver 0.0.0.0:8000 &`
3) Immediately leave terminal session. Sometimes control may get back to your user
# TO DO
## Server infrastructure
- [ ] Automate running Django process with proper env
- [x] Enforce Basic Auth authorization, to restrict access to whole website
- [x] Ensure, you cannot connect from outside the machine to postgres
## CI
- [ ] Setup Jenkins
  - [ ] Setup Testing running 
  - [ ] Setup deploys after commit
