### ISSUE TITLE
Upgrade 1.5

### ISSUE THREAD

**Issue by florczakraf** [iiuni/projektzapisy#8]
# Description

There are still some (known) tasks to do to complete upgrade to Django 1.5.
If you think that there's something else to do, feel free to update this issue.
Any help is welcome as well.
## Tasks
- [x] Update url syntax in templates
- [x] Fix usage of static files in templates
- [ ] Fix static files in rest of the project (o___O for example: https://github.com/lewymati/projektzapisy/blob/master/zapisy/apps/news/admin.py)
- [x] Update `manage.py` (because there's already warning about it's deprecation)
- [x] Figure out how to properly query if user is student or employee
- [ ] There are some other deprecation warnings that have to be eliminated
